# Generated by Django 2.2.6 on 2020-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_pic_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_p',
            new_name='tag_parent',
        ),
        migrations.AddField(
            model_name='pic_tag',
            name='tag_parent',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
