# Generated by Django 2.2.6 on 2020-01-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_pic_tag_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pic_tag',
            unique_together={('sha', 'tag', 'level', 'tag_parent')},
        ),
    ]
